---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: regapp-tls
  namespace: regapp
spec:
  backendType: akeyless
  template:
    type: kubernetes.io/tls
  data:
    - key: /k8s/regapp/tls.crt
      name: tls.crt
    - key: /k8s/regapp/tls.key
      name: tls.key