---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      # annotations:
      #   alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: regapp
    spec:
      volumes:
        - name: static-data
          emptyDir: {}

      containers:

        - name: regapp-container
          image: image-registry.openshift-image-registry.svc:5000/regapp/regapp:latest
          imagePullPolicy: IfNotPresent
          workingDir: "/code"
          command:
            - "/scripts/entrypoint.sh"
          envFrom:
            - configMapRef:
                name: regapp-configmap
            - secretRef:
                name: regapp-secrets
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: static-data
              mountPath: /static
