---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      volumes:
        - name: static-data
          emptyDir: {}

      containers:
        - name: regapp-container
          # image: regapp:latest
          image: ghcr.io/nerc-project/regapp:master
          # image: image-registry.openshift-image-registry.svc:5000/regapp/regapp:latest
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          workingDir: "/code"
          command:
            - "/scripts/entrypoint.sh"
          envFrom:
            - configMapRef:
                name: regapp-configmap
            - secretRef:
                name: regapp-secrets
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: static-data
              mountPath: /static
