apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: regapp-secrets
  namespace: regapp
spec:
  backendType: akeyless
  data:
    - key: /k8s/regapp/DJANGO_DB_NAME
      name: DJANGO_DB_NAME
    - key: /k8s/regapp/DJANGO_DB_PASSWORD
      name: DJANGO_DB_PASSWORD
    - key: /k8s/regapp/DJANGO_DB_USER
      name: DJANGO_DB_USER
    - key: /k8s/regapp/DJANGO_SECRET_KEY
      name: DJANGO_SECRET_KEY
    - key: /k8s/regapp/POSTGRES_PASSWORD
      name: POSTGRES_PASSWORD
    - key: /k8s/regapp/REGAPP_EMAIL_HOST_PASSWORD
      name: REGAPP_EMAIL_HOST_PASSWORD
    - key: /k8s/regapp/REGAPP_EMAIL_HOST_USER
      name: REGAPP_EMAIL_HOST_USER
    - key: /k8s/regapp/REGAPP_REGAPP_CLIENT_ID
      name: REGAPP_REGAPP_CLIENT_ID
    - key: /k8s/regapp/REGAPP_REGAPP_CLIENT_SECRET
      name: REGAPP_REGAPP_CLIENT_SECRET
  template:
    stringData:
      DB_URL: <%= "psql://" + data.DJANGO_DB_USER + ":" + encodeURIComponent(data.DJANGO_DB_PASSWORD) + "@regapp-db.regapp.svc.cluster.local:5432/" + data.DJANGO_DB_NAME%>
