---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      volumes:
        - name: static-data
          emptyDir: {}
      initContainers:
        - name: check-db-ready
          image: postgres:alpine
          command: ['sh', '-c',
                    'until psql -c "select now()";
                    do echo waiting for database; sleep 2; done;']
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: port
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: dbname
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: password
      containers:
        - name: regapp-container
          image: ghcr.io/nerc-project/regapp:main
          imagePullPolicy: Always
          workingDir: "/code"
          command:
            - "/scripts/entrypoint.sh"
          envFrom:
            - configMapRef:
                name: regapp-configmap
            - secretRef:
                name: regapp-secrets
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: port
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: dbname
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: regapp-postgres-ha-pguser-regapp-postgres-ha
                  key: password
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: static-data
              mountPath: /static
