---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: regapp-db-secrets
  namespace: regapp
spec:
  backendType: akeyless
  data:
    - key: /k8s/regapp/DJANGO_DB_NAME
      name: DJANGO_DB_NAME
    - key: /k8s/regapp/DJANGO_DB_PASSWORD
      name: DJANGO_DB_PASSWORD
    - key: /k8s/regapp/DJANGO_DB_USER
      name: DJANGO_DB_USER
    - key: /k8s/regapp/POSTGRES_PASSWORD
      name: POSTGRES_PASSWORD