---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: regapp-db
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: ghcr.io/nerc-project/regapp-db:master
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: regapp
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: ghcr.io/nerc-project/regapp:master
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
