---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: regapp-db
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: ghcr.io/nerc-project/regapp-db:ghcr
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: regapp
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: ghcr.io/nerc-project/regapp:ghcr
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
