---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: regapp
commonLabels:
  app.kubernetes.io/part-of: regapp

bases:
  - ../../base

resources:
  - namespace.yml
  - secrets/pgo-s3-conf.yaml
  - secrets/pgo-pgbackrest-secrets.yaml

patchesStrategicMerge:
  - patches/regapp-db.yaml
