---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: regapp
commonLabels:
  app.kubernetes.io/part-of: regapp
resources:
  # Create manually in test env so skaffold
  # does not delete...
  # - namespace.yml
  - ingress.yml
  # - test.yml

  - regapp/configmap.yml
  - regapp/cron.yml
  - regapp/regapp.yml
  - regapp/regapp_secrets_sealed.yml
  - regapp/regapp_tls_secret_sealed.yml
  - regapp/service.yml
  #
  - regapp-db/configmap.yml
  - regapp-db/regapp-db.yml
  - regapp-db/secrets_sealed.yml
  - regapp-db/service.yml
  #
  - oauth2-proxy/config.yml
  - oauth2-proxy/secret_keycloak_sealed.yml
  - oauth2-proxy/secret_cilogon_sealed.yml
  - oauth2-proxy/oauth2-proxy.yml
  - oauth2-proxy/service.yml
