---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minikube_storageclass.yml
  - ../../base

images:
  - name: ghcr.io/nerc-project/regapp-db:master
    newName: mghpcc/regapp-db
    newTag: latest
  - name: ghcr.io/nerc-project/regapp:master
    newName: mghpcc/regapp
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: minikube-dev-storage
    target:
      kind: StatefulSet

  - patch: |-
      - op: add
        path: /spec/instances/0/dataVolumeClaimSpec/storageClassName
        value: minikube-dev-storage
    target:
      kind: PostgresCluster

  - patch: |-
      - op: add
        path: /spec/backups/pgbackrest/repos/0/volume/volumeClaimSpec/storageClassName
        value: minikube-dev-storage
    target:
      kind: PostgresCluster

  - path: devel_switch.yml
