---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minikube_storageclass.yml
  - ../../base

images:
  - name: ghcr.io/nerc-project/regapp-db:master
    newName: mghpcc/regapp-db
  - name: ghcr.io/nerc-project/regapp:master
    newName: mghpcc/regapp

patches:
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: minikube-dev-storage
    target:
      kind: StatefulSet
  - path: wait_for_kc.yml
  - path: devel_switch.yml
