---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-configmap-cilogon
data:
  OAUTH2_PROXY_LOGIN_URL: https://cilogon.org/authorize?idphint=urn%3Amace%3Aincommon%3Amit.edu,https%3A%2F%2Ffed.huit.harvard.edu%2Fidp%2Fshibboleth,https%3A%2F%2Fshib.bu.edu%2Fidp%2Fshibboleth,https%3A%2F%2Fidp.xsede.org%2Fidp%2Fshibboleth,urn%3Amace%3Aincommon%3Arutgers.edu
