---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: oauth2-secret-cilogon
  namespace: regapp
spec:
  backendType: akeyless
  data:
    - key: /k8s/regapp/OAUTH2_PROXY_CLIENT_ID_CILOGON
      name: OAUTH2_PROXY_CLIENT_ID
    - key: /k8s/regapp/OAUTH2_PROXY_CLIENT_SECRET_CILOGON
      name: OAUTH2_PROXY_CLIENT_SECRET
    - key: /k8s/regapp/OAUTH2_PROXY_COOKIE_SECRET_CILOGON
      name: OAUTH2_PROXY_COOKIE_SECRET