---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sealed-secrets-operator-group
  namespace: sealed-secrets
spec:
  targetNamespaces:
  - sealed-secrets
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sealed-secrets-operator
  namespace: sealed-secrets
spec:
  channel: alpha
  name: sealed-secrets-operator-helm
  source: regapp-operatorhub-catalog
  sourceNamespace: openshift-marketplace
