---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minikube_storageclass.yml
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: minikube-dev-storage
    target:
      kind: StatefulSet
  - patch: |-
      - op: replace
        path: /spec/source
        value: operatorhubio-catalog
    target:
      kind: Subscription
  - patch: |-
      - op: replace
        path: /spec/sourceNamespace
        value: olm
    target:
      kind: Subscription
